public CdlMorningStar { get; set; }
public CdlGapSideSideWhite { get; set; }
public CdlGravestoneDoji { get; set; }
public CdlHammer { get; set; }
public CdlHangingMan { get; set; }
public CdlHarami { get; set; }
public CdlHaramiCross { get; set; }
public CdlHignWave { get; set; }
public CdlHikkake { get; set; }
public CdlHikkakeMod { get; set; }
public CdlHomingPigeon { get; set; }
public CdlIdentical3Crows { get; set; }
public CdlInNeck { get; set; }
public CdlInvertedHammer { get; set; }
public CdlKicking { get; set; }
public CdlLadderBottom { get; set; }
public CdlKickingByLength { get; set; }
public CdlLongLeggedDoji { get; set; }
public CdlLongLine { get; set; }
public CdlMarubozu { get; set; }
public CdlMatHold { get; set; }
public CdlMatchingLow { get; set; }
public CdlMorningDojiStar { get; set; }
public CdlMorningStar { get; set; }
public CdlOnNeck { get; set; }
public CdlPiercing	{ get; set; }
public CdlRickshawMan	{ get; set; }
public CdlRiseFall3Methods	{ get; set; }
public CdlSeperatingLines	{ get; set; }
public CdlShootingStar	{ get; set; }
public CdlShortLine	{ get; set; }
public CdlSpinningTop	{ get; set; }
public CdlStalledPattern	{ get; set; }
public CdlStickSandwhich	{ get; set; }
public CdlTakuri	{ get; set; }
public CdlTasukiGap	{ get; set; }
public CdlThrusting	{ get; set; }
public CdlTristar	{ get; set; }
public CdlUnique3River	{ get; set; }
public CdlUpsideGap2Crows	{ get; set; }
public CdlXSideGap3Methods	{ get; set; }
public Ceil	{ get; set; }
public Cmo	{ get; set; }
public Cos	{ get; set; }
public Cosh	{ get; set; }
public Dema	{ get; set; }
public Div	{ get; set; }
public Dx	{ get; set; }
public Ema	{ get; set; }
public Exp	{ get; set; }
public Floor	{ get; set; }
public HtDcPeriod	{ get; set; }
public HtDcPhase	{ get; set; }
public HtPhasor	{ get; set; }
public HtSine	{ get; set; }
public HtTrendline	{ get; set; }
public HtTrendMode	{ get; set; }
public Kama	{ get; set; }
public LinearReg	{ get; set; }
public LinearRegAngle	{ get; set; }
public LinearRegIntercept	{ get; set; }
public LinearRegSlope	{ get; set; }
public Ln	{ get; set; }
public Log10	{ get; set; }
public MacdExt	{ get; set; }
public MacdFix	{ get; set; }
public Mama	{ get; set; }
public Max	{ get; set; }
public MaxIndex	{ get; set; }
public MedPrice	{ get; set; }
public Mfi	{ get; set; }
public MidPoint	{ get; set; }
public MidPrice	{ get; set; }
public Min	{ get; set; }
public MinIndex	{ get; set; }
public MinMax	{ get; set; }
public MinusDI	{ get; set; }
public MinusDM	{ get; set; }
public Mom	{ get; set; }
public MovingAverage	{ get; set; }
public MovingAverageVariablePeriod	{ get; set; }
public Mult	{ get; set; }
public Natr	{ get; set; }
public Obv	{ get; set; }
public PlusDI	{ get; set; }
public PlusDM	{ get; set; }
public Ppo	{ get; set; }
public Roc	{ get; set; }
public RocP	{ get; set; }
public RocR	{ get; set; }
public RocR100	{ get; set; }
public Sar	{ get; set; }
public SarExt	{ get; set; }
public Sin	{ get; set; }
public Sinh	{ get; set; }
public Sma	{ get; set; }
public Sqrt	{ get; set; }
public StdDev	{ get; set; }
public StochF	{ get; set; }
public StochRsi	{ get; set; }
public Sub	{ get; set; }
public Sum	{ get; set; }
public T3	{ get; set; }
public Tan	{ get; set; }
public Tanh	{ get; set; }
public Tema	{ get; set; }
public Trima	{ get; set; }
public Trix	{ get; set; }
public TrueRange	{ get; set; }
public Tsf	{ get; set; }
public TypPrice	{ get; set; }
public UltOsc	{ get; set; }
public WclPrice	{ get; set; }
public Variance	{ get; set; }
public WillR	{ get; set; }
public Wma	{ get; set; }
